logger: true
arch: "rfnet"
depth: 16
s: 0.0001
workers: 4
multi-gpu: false
batch-size: 256
test-batch-size: 256
admm-epochs: 1
optmzr: "adam"
lr: 0.001
lr-decay: 30
momentum: 0.9
weight-decay: 0.0001
no-cuda: false
seed: 1
log-interval: 159
save-model: ""
masked-retrain: true
verbose: false
admm: false
rho: 0.0001
rho-num: 4
sparsity-type: "irregular"
combine-progressive: false
lr-scheduler: "default"
warmup: false
warmup-lr: 0.0001
warmup-epochs: 0
mixup: false
alpha: 0.0
smooth: false
smooth-eps: 0.0
no-tricks: false
dataset: "dronerc"
task-folder: "tasks-sw-nonorm-0db"
exp-name: "exp-radar-0db"
base-path: ""
save-path: ""
input-size: 2048 # 16382
classes: 6
tasks: 1
mask: ""
config-file: ""
config-setting: "1"
config-shrink: 0.5
heritage-weight: false ###
adaptive-mask: true
admm-mask: false
adaptive-ratio: 0.2
epochs: 100
epochs-prune: 30
epochs-mask-retrain: 30
mask-admm-epochs: 1
load-model: "" #"radar/exp-radar-mixed-3offset/task0/rfnet16.pt" 
load-model-pruned: "" # "radar/exp-radar-mixed-splitheads/task0/retrained.pt"